apiVersion: v1
entries:
  urbancodedeploy:
  - apiVersion: v1
    created: 2018-07-16T23:14:23.863382+02:00
    description: A Helm chart for IBM UrbanCode Deploy
    digest: 213c135cb209b7c1754aab8d249ce93c37f3b6bdbbfe2ec29fa02cddedcbab94
    icon: https://github.com/niklaushirt/urbancode_chart/raw/master/icons/urbancodedeployicon.png
    maintainers:
    - email: niklaushirt@gmail.com
      name: Niklaus Hirt
    name: urbancodedeploy
    sources:
    - https://github.com/niklaushirt/urbancode_chart
    urls:
    - https://raw.githubusercontent.com/niklaushirt/charts/master/charts/repo/stable/urbancodedeploy-7.0.0.tgz
    version: 7.0.0
generated: 2018-07-16T23:14:23.862728+02:00
