apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ucd-server
  name: ucd-server
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - name: "https"
    port: 8443
    targetPort: 8443
    nodePort: 30123
  - name: "agentcomm"
    port: 7918
    targetPort: 7918
  selector:
    io.kompose.service: ucd-server
status:
  loadBalancer: {}
